import * as THREE from 'https://unpkg.com/three@0.160.0/build/three.module.js';
import {OrbitControls} from 'https://unpkg.com/three@0.160.0/examples/jsm/controls/OrbitControls.js';
import {TransformControls} from 'https://unpkg.com/three@0.160.0/examples/jsm/controls/TransformControls.js';
import {SVGLoader} from 'https://unpkg.com/three@0.160.0/examples/jsm/loaders/SVGLoader.js';
import {FontLoader} from 'https://unpkg.com/three@0.160.0/examples/jsm/loaders/FontLoader.js';
import {GLTFExporter} from 'https://unpkg.com/three@0.160.0/examples/jsm/exporters/GLTFExporter.js';
import {mergeGeometries} from 'https://unpkg.com/three@0.160.0/examples/jsm/utils/BufferGeometryUtils.js';
import {Brush,Evaluator,ADDITION,SUBTRACTION,INTERSECTION} from 'https://cdn.jsdelivr.net/npm/three-bvh-csg@0.0.16/+esm';
import * as pdfjs from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/build/pdf.min.mjs';
const $=id=>document.getElementById(id),stage=$('stage'),scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true}),camera=new THREE.PerspectiveCamera(45,1,.1,20000),orbit=new OrbitControls(camera,renderer.domElement),root=new THREE.Group(),grid=new THREE.GridHelper(1000,50,0x293348,0x151b24),ray=new THREE.Raycaster(),mouse=new THREE.Vector2(),transform=new TransformControls(camera,renderer.domElement);
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;stage.appendChild(renderer.domElement);camera.position.set(0,-180,130);orbit.enableDamping=true;grid.rotation.x=Math.PI/2;grid.position.z=-8;scene.add(root,grid,transform);
const hemi=new THREE.HemisphereLight(0xc7dbff,0x111620,2.1),key=new THREE.DirectionalLight(0xffffff,4.5),rim=new THREE.DirectionalLight(0x7766ff,2.2);key.position.set(160,-120,220);rim.position.set(-130,110,100);scene.add(hemi,key,rim);transform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);transform.addEventListener('objectChange',()=>syncFromMesh());
let parts=[],sel=null,id=1,project='modelo',auto=false,font=null;
function status(t,err=false){$('status').textContent=t;$('status').style.color=err?'#ff8095':'#84dca8'}
function resize(){renderer.setSize(stage.clientWidth,stage.clientHeight,false);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
(function loop(){requestAnimationFrame(loop);if(auto)root.rotation.z+=.003;orbit.update();renderer.render(scene,camera)})();
function mat(p){let color=p.color,rough=.72,metal=.04;if(p.finish==='gloss'){rough=.15;metal=.08}if(p.finish==='metal'){rough=.25;metal=.9}if(p.finish==='plastic'){rough=.35;metal=.02}if(p.finish==='gold'){color='#d4af37';rough=.2;metal=.95}if(p.finish==='chrome'){color='#d9e0e8';rough=.08;metal=1}return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,side:THREE.DoubleSide})}
function rr(w,h,r=0){let s=new THREE.Shape(),x=-w/2,y=-h/2;r=Math.min(r,w/2,h/2);s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function ellipse(rx,ry){let s=new THREE.Shape();s.absellipse(0,0,rx,ry,0,Math.PI*2);return s}function poly(r,n){let s=new THREE.Shape();for(let i=0;i<n;i++){let a=-Math.PI/2+i*Math.PI*2/n,x=Math.cos(a)*r,y=Math.sin(a)*r;i?s.lineTo(x,y):s.moveTo(x,y)}s.closePath();return s}function star(r,n=5){let s=new THREE.Shape();for(let i=0;i<n*2;i++){let q=i%2?r*.45:r,a=-Math.PI/2+i*Math.PI/n,x=Math.cos(a)*q,y=Math.sin(a)*q;i?s.lineTo(x,y):s.moveTo(x,y)}s.closePath();return s}function tri(w,h){let s=new THREE.Shape();s.moveTo(0,-h/2);s.lineTo(w/2,h/2);s.lineTo(-w/2,h/2);s.closePath();return s}function diamond(w,h){let s=new THREE.Shape();s.moveTo(0,-h/2);s.lineTo(w/2,0);s.lineTo(0,h/2);s.lineTo(-w/2,0);s.closePath();return s}function arrow(w,h){let s=new THREE.Shape(),a=w*.22,b=w*.45,c=h*.15;s.moveTo(-a,h/2);s.lineTo(a,h/2);s.lineTo(a,c);s.lineTo(b,c);s.lineTo(0,-h/2);s.lineTo(-b,c);s.lineTo(-a,c);s.closePath();return s}
function geometry(p){if(p.type==='raw'){let g=new THREE.BufferGeometry(),o=p.opt;g.setAttribute('position',new THREE.Float32BufferAttribute(o.pos,3));if(o.norm?.length)g.setAttribute('normal',new THREE.Float32BufferAttribute(o.norm,3));if(o.idx?.length)g.setIndex(o.idx);if(!o.norm?.length)g.computeVertexNormals();return g}if(p.type!=='extrude'){let o=p.opt||{};switch(p.type){case'box':return new THREE.BoxGeometry(o.w,o.h,o.d);case'sphere':return new THREE.SphereGeometry(o.r,24,16);case'cylinder':return new THREE.CylinderGeometry(o.r,o.r,o.h,24);case'cone':return new THREE.ConeGeometry(o.r,o.h,24);case'pyramid':return new THREE.CylinderGeometry(0,o.r,o.h,o.s||4);case'torus':return new THREE.TorusGeometry(o.r,o.t||3,12,32);case'capsule':return new THREE.CapsuleGeometry(o.r,o.h,4,12)}}return new THREE.ExtrudeGeometry(p.shape,{depth:p.depth,bevelEnabled:p.bevel>0,bevelThickness:p.bevel,bevelSize:p.bevel,bevelSegments:2,curveSegments:16})}
function rebuild(p){if(p.mesh){root.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose()}let g=geometry(p);g.computeVertexNormals();p.mesh=new THREE.Mesh(g,mat(p));p.mesh.userData.id=p.id;p.mesh.name=p.name;p.mesh.position.copy(p.pos);p.mesh.rotation.copy(p.rot);p.mesh.scale.copy(p.scale);p.mesh.visible=p.visible;root.add(p.mesh);if(sel===p.id)transform.attach(p.mesh);renderLayers();stats()}
function add(o){let p={id:id++,name:o.name||'Peça',type:o.type||'extrude',shape:o.shape||null,opt:o.opt||{},depth:o.depth??8,bevel:o.bevel??.5,color:o.color||'#775cff',finish:o.finish||'matte',pos:o.pos||new THREE.Vector3(),rot:o.rot||new THREE.Euler(),scale:o.scale||new THREE.Vector3(1,o.type&&o.type!=='extrude'?1:-1,1),visible:true};parts.push(p);rebuild(p);select(p.id);fit();return p}
function clear(){transform.detach();parts.forEach(p=>{root.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose()});parts=[];sel=null;renderLayers();stats()}
function selected(){return parts.find(p=>p.id===sel)}
function select(n){sel=n;let p=selected();if(!p){transform.detach();$('selected').textContent='Nenhuma';return}transform.attach(p.mesh);$('selected').textContent=p.name;syncUI(p);renderLayers()}
function syncUI(p){$('name').value=p.name;$('depth').value=p.depth;$('bevel').value=p.bevel;$('px').value=p.pos.x.toFixed(2);$('py').value=p.pos.y.toFixed(2);$('pz').value=p.pos.z.toFixed(2);$('rx').value=THREE.MathUtils.radToDeg(p.rot.x).toFixed(1);$('ry').value=THREE.MathUtils.radToDeg(p.rot.y).toFixed(1);$('rz').value=THREE.MathUtils.radToDeg(p.rot.z).toFixed(1);$('sx').value=p.scale.x.toFixed(2);$('sy').value=p.scale.y.toFixed(2);$('sz').value=p.scale.z.toFixed(2);$('color').value=p.color;$('finish').value=p.finish}
function syncFromMesh(){let p=selected();if(!p)return;p.pos.copy(p.mesh.position);p.rot.copy(p.mesh.rotation);p.scale.copy(p.mesh.scale);syncUI(p)}
function renderLayers(){$('layers').innerHTML='';$('count').textContent=parts.length;parts.forEach(p=>{let d=document.createElement('div');d.className='layer'+(p.id===sel?' active':'');d.innerHTML=`<button class="eye">${p.visible?'●':'○'}</button><span>${p.name}</span><i class="dot" style="background:${p.color}"></i>`;d.onclick=e=>{if(e.target.classList.contains('eye')){p.visible=!p.visible;p.mesh.visible=p.visible;renderLayers()}else select(p.id)};$('layers').appendChild(d)})}
function stats(){let t=0;parts.forEach(p=>{let g=p.mesh?.geometry;if(g)t+=g.index?g.index.count/3:g.attributes.position.count/3});$('stats').textContent=`${Math.round(t).toLocaleString('pt-BR')} triângulos`}
function fit(){if(!parts.length)return;let b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),m=Math.max(s.x,s.y,s.z,20),d=m/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)))*1.5;camera.position.set(c.x,c.y-d*.8,c.z+d*.7);orbit.target.copy(c);orbit.update()}
function centerAll(){let b=new THREE.Box3().setFromObject(root),c=b.getCenter(new THREE.Vector3());parts.forEach(p=>{p.pos.sub(c);p.mesh.position.copy(p.pos)})}
async function parseSVG(text){clear();let data=new SVGLoader().parse(text),n=1;data.paths.forEach(path=>{let color='#'+path.color.getHexString();SVGLoader.createShapes(path).forEach(s=>add({name:`SVG ${n++}`,shape:s,color,depth:8,bevel:.5}))});centerAll();fit();status(`SVG importado: ${parts.length} peças`)}
async function rasterToSVG(imgd){return ImageTracer.imagedataToSVG(imgd,{ltres:1,qtres:1,pathomit:8,colorsampling:2,numberofcolors:8,viewbox:true,roundcoords:1,linefilter:true,strokewidth:0,desc:false})}
async function importImage(file){let url=URL.createObjectURL(file),im=new Image();await new Promise((r,j)=>{im.onload=r;im.onerror=j;im.src=url});let k=Math.min(1,900/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*k;c.height=im.height*k;let x=c.getContext('2d');x.drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(url);await parseSVG(await rasterToSVG(x.getImageData(0,0,c.width,c.height)))}
async function importPDF(file){pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/build/pdf.worker.min.mjs';let doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,page=await doc.getPage(1),v=page.getViewport({scale:2}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;let x=c.getContext('2d');await page.render({canvasContext:x,viewport:v}).promise;await parseSVG(await rasterToSVG(x.getImageData(0,0,c.width,c.height)));status('PDF importado pela primeira página')}
async function importDXF(file){if(!window.DxfParser)throw Error('DxfParser indisponível');let d=new DxfParser().parseSync(await file.text());clear();let n=1;(d.entities||[]).forEach(e=>{if((e.type==='LWPOLYLINE'||e.type==='POLYLINE')&&e.vertices?.length>=3){let s=new THREE.Shape();s.moveTo(e.vertices[0].x,e.vertices[0].y);e.vertices.slice(1).forEach(v=>s.lineTo(v.x,v.y));s.closePath();add({name:`DXF ${n++}`,shape:s,depth:6})}if(e.type==='CIRCLE')add({name:`DXF círculo ${n++}`,shape:ellipse(e.radius,e.radius),depth:6,pos:new THREE.Vector3(e.center.x,e.center.y,0)})});centerAll();fit();status(`DXF: ${parts.length} peças`)}
async function open(file){if(!file)return;project=file.name.replace(/\.[^.]+$/,'');$('fileName').textContent=file.name;let n=file.name.toLowerCase();try{if(n.endsWith('.svg'))await parseSVG(await file.text());else if(n.endsWith('.pdf'))await importPDF(file);else if(n.endsWith('.dxf'))await importDXF(file);else if(n.endsWith('.json'))loadJSON(JSON.parse(await file.text()));else if(file.type.startsWith('image/'))await importImage(file);else throw Error('Formato não suportado')}catch(e){console.error(e);status(e.message,true)}}
function shapeAdd(){let mode=$('shapeMode').value,w=+$('sw').value||40,h=+$('sh').value||25,d=+$('sd').value||8,r=+$('sr').value||16,n=+$('ssides').value||6,color=$('scolor').value;if(mode==='3d'){let t=$('shape3d').value,o=t==='box'?{w,h,d}:t==='sphere'?{r}:t==='torus'?{r,t:d*.25}:t==='capsule'?{r:r*.5,h}:t==='pyramid'?{r,h,s:n}:{r,h};add({name:t,type:t,opt:o,color,scale:new THREE.Vector3(1,1,1)})}else{let t=$('shape2d').value,s=t==='rect'?rr(w,h):t==='round'?rr(w,h,Math.min(w,h)*.15):t==='square'?rr(w,w):t==='circle'?ellipse(r,r):t==='ellipse'?ellipse(w/2,h/2):t==='triangle'?tri(w,h):t==='diamond'?diamond(w,h):t==='pentagon'?poly(r,5):t==='hexagon'?poly(r,6):t==='octagon'?poly(r,8):t==='star'?star(r,n):arrow(w,h);add({name:t,shape:s,depth:d,color})}}
async function addText(){let text=$('textInput').value.trim();if(!text)return;if(!font)font=await new FontLoader().loadAsync('https://unpkg.com/three@0.160.0/examples/fonts/helvetiker_bold.typeface.json');let list=font.generateShapes(text,+$('textSize').value||28);list.forEach((s,i)=>add({name:`Texto ${i+1}`,shape:s,depth:+$('textDepth').value||8,color:$('textColor').value,finish:'gold'}));centerAll();fit()}
function raw(g){return{pos:Array.from(g.attributes.position.array),norm:g.attributes.normal?Array.from(g.attributes.normal.array):[],idx:g.index?Array.from(g.index.array):[]}}
function bool(op){let a=parts.filter(p=>p.visible&&!p.isBase).slice(0,2);if(a.length<2)return status('Deixe 2 peças visíveis',true);try{a.forEach(p=>p.mesh.updateMatrixWorld(true));let ga=a[0].mesh.geometry.clone(),gb=a[1].mesh.geometry.clone();ga.applyMatrix4(a[0].mesh.matrixWorld);gb.applyMatrix4(a[1].mesh.matrixWorld);let A=new Brush(ga),B=new Brush(gb),ev=new Evaluator(),res=ev.evaluate(A,B,op==='union'?ADDITION:op==='subtract'?SUBTRACTION:INTERSECTION);res.geometry.computeVertexNormals();let c=a[0].color;a.forEach(remove);add({name:`Boolean ${op}`,type:'raw',opt:raw(res.geometry),color:c,scale:new THREE.Vector3(1,1,1)});ga.dispose();gb.dispose();res.geometry.dispose();fit();status(`Boolean ${op} concluído`)}catch(e){console.error(e);status('Falha na booleana',true)}}
function remove(p){if(!p)return;root.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();parts=parts.filter(x=>x!==p);if(sel===p.id){sel=null;transform.detach()}renderLayers();stats()}
function relief(v){let p=selected();if(!p)return;if(p.type==='extrude'){p.depth=Math.max(.5,p.depth+v);rebuild(p)}else{p.pos.z+=v;p.mesh.position.copy(p.pos)}syncUI(p)}
function base(){let old=parts.find(p=>p.isBase);if(old)remove(old);let b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),pad=+$('basePad').value||12,dep=+$('baseDepth').value||4,p=add({name:'Base',shape:rr(s.x+pad*2,s.y+pad*2,10),depth:dep,color:'#eeeeee',finish:'plastic',scale:new THREE.Vector3(1,1,1),pos:new THREE.Vector3(c.x,c.y,b.min.z-dep-1)});p.isBase=true;fit()}
function optimize(){parts.forEach(p=>{if(p.type==='extrude'){p.bevel=Math.min(p.bevel,.4);rebuild(p)}});status('Otimização Roblox aplicada')}
function exportGLB(obj,name){new GLTFExporter().parse(obj,r=>{let b=new Blob([r],{type:'model/gltf-binary'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},{binary:true,onlyVisible:true})}
function merged(){let gs=parts.filter(p=>p.visible).map(p=>{p.mesh.updateMatrixWorld(true);let g=p.mesh.geometry.clone();g.applyMatrix4(p.mesh.matrixWorld);return g}),g=mergeGeometries(gs,false);if(!g)return status('Falha ao mesclar',true);let m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0xffffff})),q=new THREE.Group();q.add(m);exportGLB(q,project+'-mesclado');setTimeout(()=>{g.dispose();m.material.dispose()},1200)}
function saveJSON(){let data={version:8,name:project,parts:parts.map(p=>({name:p.name,type:p.type,opt:p.opt,points:p.shape?p.shape.getPoints(24).map(v=>[v.x,v.y]):null,depth:p.depth,bevel:p.bevel,color:p.color,finish:p.finish,pos:p.pos.toArray(),rot:[p.rot.x,p.rot.y,p.rot.z],scale:p.scale.toArray(),visible:p.visible,isBase:!!p.isBase}))},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download=project+'-corel3d.json';a.click()}
function loadJSON(d){clear();project=d.name||'projeto';(d.parts||[]).forEach(q=>{let s=q.points?new THREE.Shape(q.points.map(v=>new THREE.Vector2(...v))):null,p=add({name:q.name,type:q.type,shape:s,opt:q.opt,depth:q.depth,bevel:q.bevel,color:q.color,finish:q.finish,pos:new THREE.Vector3(...q.pos),rot:new THREE.Euler(...q.rot),scale:new THREE.Vector3(...q.scale)});p.visible=q.visible!==false;p.mesh.visible=p.visible;p.isBase=q.isBase});fit();status('Projeto aberto')}
function environment(){let b=$('bg').value;scene.background=new THREE.Color(b==='white'?0xf2f2f2:b==='gray'?0x393d46:b==='blue'?0x071a35:0x080b11);let l=$('light').value;if(l==='soft'){hemi.intensity=3;key.intensity=2;rim.intensity=1}else if(l==='dramatic'){hemi.intensity=.7;key.intensity=6;rim.intensity=4}else if(l==='flat'){hemi.intensity=4;key.intensity=.5;rim.intensity=0}else{hemi.intensity=2.1;key.intensity=4.5;rim.intensity=2.2}}
$('file').onchange=e=>open(e.target.files[0]);document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{let m=b.dataset.open;$('file').accept=m==='svg'?'.svg':m==='pdf'?'.pdf':m==='dxf'?'.dxf':'image/*';$('file').click()});$('loadProject').onclick=()=>{$('file').accept='.json';$('file').click()};$('saveProject').onclick=saveJSON;$('addShape').onclick=shapeAdd;$('addText').onclick=addText;$('union').onclick=()=>bool('union');$('subtract').onclick=()=>bool('subtract');$('intersect').onclick=()=>bool('intersect');$('relief').onclick=()=>relief(2);$('basrelief').onclick=()=>relief(-2);$('mx').onclick=()=>{let p=selected();if(p){p.scale.x*=-1;p.mesh.scale.copy(p.scale);syncUI(p)}};$('my').onclick=()=>{let p=selected();if(p){p.scale.y*=-1;p.mesh.scale.copy(p.scale);syncUI(p)}};$('mz').onclick=()=>{let p=selected();if(p){p.scale.z*=-1;p.mesh.scale.copy(p.scale);syncUI(p)}};$('center').onclick=()=>{let p=selected();if(p){p.pos.x=p.pos.y=0;p.mesh.position.copy(p.pos);syncUI(p)}};$('ground').onclick=()=>{let p=selected();if(p){let b=new THREE.Box3().setFromObject(p.mesh);p.pos.z-=b.min.z;p.mesh.position.copy(p.pos);syncUI(p)}};$('move').onclick=()=>transform.setMode('translate');$('rotate').onclick=()=>transform.setMode('rotate');$('scale').onclick=()=>transform.setMode('scale');$('duplicate').onclick=()=>{let p=selected();if(!p)return;let q={...p,id:id++,name:p.name+' cópia',pos:p.pos.clone().add(new THREE.Vector3(5,5,2)),rot:p.rot.clone(),scale:p.scale.clone(),mesh:null};parts.push(q);rebuild(q);select(q.id)};$('delete').onclick=()=>remove(selected());$('base').onclick=base;$('removeBase').onclick=()=>remove(parts.find(p=>p.isBase));$('roblox').onclick=optimize;$('exportOne').onclick=()=>{let p=selected();if(p){let g=new THREE.Group(),m=p.mesh.clone();m.geometry=p.mesh.geometry.clone();m.material=p.mesh.material.clone();g.add(m);exportGLB(g,project+'-'+p.name)}};$('exportAll').onclick=()=>exportGLB(root,project+'-3d-v8');$('exportMerged').onclick=merged;$('snapshot').onclick=()=>{renderer.render(scene,camera);let a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download=project+'-preview.png';a.click()};$('bg').onchange=environment;$('light').onchange=environment;$('autorotate').onchange=e=>auto=e.target.checked;
$('name').onchange=e=>{let p=selected();if(p){p.name=e.target.value;p.mesh.name=p.name;renderLayers()}};$('depth').oninput=e=>{let p=selected();if(p&&p.type==='extrude'){p.depth=+e.target.value;rebuild(p)}};$('bevel').oninput=e=>{let p=selected();if(p&&p.type==='extrude'){p.bevel=+e.target.value;rebuild(p)}};$('color').oninput=e=>{let p=selected();if(p){p.color=e.target.value;p.mesh.material.dispose();p.mesh.material=mat(p);renderLayers()}};$('finish').onchange=e=>{let p=selected();if(p){p.finish=e.target.value;p.mesh.material.dispose();p.mesh.material=mat(p)}};[['px','x'],['py','y'],['pz','z']].forEach(([i,a])=>$(i).oninput=e=>{let p=selected();if(p){p.pos[a]=+e.target.value;p.mesh.position.copy(p.pos)}});[['rx','x'],['ry','y'],['rz','z']].forEach(([i,a])=>$(i).oninput=e=>{let p=selected();if(p){p.rot[a]=THREE.MathUtils.degToRad(+e.target.value);p.mesh.rotation.copy(p.rot)}});[['sx','x'],['sy','y'],['sz','z']].forEach(([i,a])=>$(i).oninput=e=>{let p=selected();if(p){p.scale[a]=+e.target.value||.01;p.mesh.scale.copy(p.scale)}});
renderer.domElement.addEventListener('pointerdown',e=>{if(transform.dragging)return;let r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);let h=ray.intersectObjects(parts.map(p=>p.mesh));if(h[0])select(h[0].object.userData.id)});addEventListener('keydown',e=>{if(e.key.toLowerCase()==='w')transform.setMode('translate');if(e.key.toLowerCase()==='e')transform.setMode('rotate');if(e.key.toLowerCase()==='r')transform.setMode('scale')});environment();renderLayers();stats();