(()=>{
'use strict';
const $=id=>document.getElementById(id);
function fail(msg,e){console.error(msg,e||'');const s=$('status');if(s){s.textContent=msg;s.style.color='#ff8da0'}const eng=$('engine');if(eng){eng.textContent='ERRO NO MOTOR 3D';eng.style.background='#35131a';eng.style.color='#ff8da0'}}
try{
if(!window.THREE) throw new Error('Three.js não carregou');
const stage=$('stage');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x090d14);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;stage.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(45,1,.1,10000);camera.position.set(0,-160,110);
const orbit=new THREE.OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;
const root=new THREE.Group();scene.add(root);
const grid=new THREE.GridHelper(800,40,0x33405a,0x18202c);grid.rotation.x=Math.PI/2;grid.position.z=-8;scene.add(grid);
scene.add(new THREE.HemisphereLight(0xdce8ff,0x151923,1.6));const dl=new THREE.DirectionalLight(0xffffff,2.7);dl.position.set(100,-100,160);scene.add(dl);const dl2=new THREE.DirectionalLight(0x7766ff,1.3);dl2.position.set(-100,80,80);scene.add(dl2);
let transform=null;if(THREE.TransformControls){transform=new THREE.TransformControls(camera,renderer.domElement);transform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);scene.add(transform)}
let parts=[],selectedId=null,nextId=1,autorotate=false,font=null;
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
function status(t,err=false){$('status').textContent=t;$('status').style.color=err?'#ff8da0':'#84dca8'}
function resize(){const w=Math.max(1,stage.clientWidth),h=Math.max(1,stage.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
(function loop(){requestAnimationFrame(loop);if(autorotate)root.rotation.z+=.003;orbit.update();renderer.render(scene,camera)})();
function material(p){let c=p.color||'#775cff',rough=.65,metal=.05;if(p.finish==='gloss'){rough=.15}if(p.finish==='metal'){rough=.25;metal=.9}if(p.finish==='plastic'){rough=.3}if(p.finish==='gold'){c='#d4af37';rough=.18;metal=.95}if(p.finish==='chrome'){c='#dbe2ea';rough=.07;metal=1}return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal,side:THREE.DoubleSide})}
function rr(w,h,r=0){const s=new THREE.Shape(),x=-w/2,y=-h/2;r=Math.min(r,w/2,h/2);s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s}
function ellipse(rx,ry){const s=new THREE.Shape();s.absellipse(0,0,rx,ry,0,Math.PI*2,false);return s}
function poly(r,n){const s=new THREE.Shape();for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,x=Math.cos(a)*r,y=Math.sin(a)*r;i?s.lineTo(x,y):s.moveTo(x,y)}s.closePath();return s}
function tri(w,h){const s=new THREE.Shape();s.moveTo(0,-h/2);s.lineTo(w/2,h/2);s.lineTo(-w/2,h/2);s.closePath();return s}
function diamond(w,h){const s=new THREE.Shape();s.moveTo(0,-h/2);s.lineTo(w/2,0);s.lineTo(0,h/2);s.lineTo(-w/2,0);s.closePath();return s}
function star(r,n=5){const s=new THREE.Shape();for(let i=0;i<n*2;i++){const q=i%2?r*.45:r,a=-Math.PI/2+i*Math.PI/n,x=Math.cos(a)*q,y=Math.sin(a)*q;i?s.lineTo(x,y):s.moveTo(x,y)}s.closePath();return s}
function arrow(w,h){const s=new THREE.Shape(),a=w*.2,b=w*.45,c=h*.15;s.moveTo(-a,h/2);s.lineTo(a,h/2);s.lineTo(a,c);s.lineTo(b,c);s.lineTo(0,-h/2);s.lineTo(-b,c);s.lineTo(-a,c);s.closePath();return s}
function geometry(p){if(p.kind==='box')return new THREE.BoxGeometry(p.w,p.h,p.d);if(p.kind==='sphere')return new THREE.SphereGeometry(p.r,32,20);if(p.kind==='cylinder')return new THREE.CylinderGeometry(p.r,p.r,p.h,32);if(p.kind==='cone')return new THREE.ConeGeometry(p.r,p.h,32);if(p.kind==='pyramid')return new THREE.CylinderGeometry(0,p.r,p.h,Math.max(3,p.sides||4));if(p.kind==='torus')return new THREE.TorusGeometry(p.r,Math.max(1,p.d*.25),16,48);return new THREE.ExtrudeGeometry(p.shape,{depth:p.depth,bevelEnabled:p.bevel>0,bevelThickness:p.bevel,bevelSize:p.bevel,bevelSegments:2,curveSegments:20})}
function rebuild(p){if(p.mesh){root.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose()}p.mesh=new THREE.Mesh(geometry(p),material(p));p.mesh.userData.partId=p.id;p.mesh.name=p.name;p.mesh.position.copy(p.pos);p.mesh.rotation.copy(p.rot);p.mesh.scale.copy(p.scale);root.add(p.mesh);if(selectedId===p.id&&transform)transform.attach(p.mesh);renderLayers();updateStats()}
function addPart(o){const p={id:nextId++,name:o.name||'Peça',kind:o.kind||'extrude',shape:o.shape||null,w:o.w||20,h:o.h||20,d:o.d||8,r:o.r||12,sides:o.sides||4,depth:o.depth||8,bevel:o.bevel??.6,color:o.color||'#775cff',finish:o.finish||'matte',pos:new THREE.Vector3(),rot:new THREE.Euler(),scale:new THREE.Vector3(1,o.kind&&o.kind!=='extrude'?1:-1,1),mesh:null};parts.push(p);rebuild(p);select(p.id);fit();status('Forma adicionada com sucesso');return p}
function selected(){return parts.find(p=>p.id===selectedId)||null}
function renderLayers(){$('layers').innerHTML='';$('count').textContent=parts.length;parts.forEach(p=>{const d=document.createElement('div');d.className='layer'+(p.id===selectedId?' active':'');d.innerHTML=`<span>${p.name}</span><i class="dot" style="background:${p.color}"></i>`;d.onclick=()=>select(p.id);$('layers').appendChild(d)})}
function select(id){selectedId=id;const p=selected();if(!p){$('selected').textContent='Nenhuma';if(transform)transform.detach();return}$('selected').textContent=p.name;$('name').value=p.name;$('depth').value=p.depth;$('bevel').value=p.bevel;$('px').value=p.pos.x.toFixed(2);$('py').value=p.pos.y.toFixed(2);$('pz').value=p.pos.z.toFixed(2);$('rx').value=THREE.MathUtils.radToDeg(p.rot.x).toFixed(1);$('ry').value=THREE.MathUtils.radToDeg(p.rot.y).toFixed(1);$('rz').value=THREE.MathUtils.radToDeg(p.rot.z).toFixed(1);$('sx').value=p.scale.x.toFixed(2);$('sy').value=p.scale.y.toFixed(2);$('sz').value=p.scale.z.toFixed(2);$('color').value=p.color;$('finish').value=p.finish;if(transform)transform.attach(p.mesh);renderLayers()}
function updateStats(){let t=0;parts.forEach(p=>{const g=p.mesh.geometry;t+=g.index?g.index.count/3:g.attributes.position.count/3});$('stats').textContent=`${Math.round(t).toLocaleString('pt-BR')} triângulos`}
function fit(){if(!parts.length)return;const b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),m=Math.max(s.x,s.y,s.z,20),d=m/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)))*1.45;camera.position.set(c.x,c.y-d*.8,c.z+d*.7);orbit.target.copy(c);orbit.update()}
function addShape(){const mode=$('shapeMode').value,w=+$('sw').value||40,h=+$('sh').value||25,d=+$('sd').value||8,r=+$('sr').value||16,n=Math.max(3,+$('ssides').value||6),color=$('scolor').value;if(mode==='3d'){const k=$('shape3d').value;addPart({name:k,kind:k,w,h,d,r,sides:n,color})}else{const k=$('shape2d').value;let s=k==='rect'?rr(w,h):k==='round'?rr(w,h,Math.min(w,h)*.15):k==='square'?rr(w,w):k==='circle'?ellipse(r,r):k==='ellipse'?ellipse(w/2,h/2):k==='triangle'?tri(w,h):k==='diamond'?diamond(w,h):k==='pentagon'?poly(r,5):k==='hexagon'?poly(r,6):k==='octagon'?poly(r,8):k==='star'?star(r,n):arrow(w,h);addPart({name:k,shape:s,depth:d,color})}}
async function addText(){try{const text=$('textInput').value.trim();if(!text)return;if(!THREE.FontLoader)throw new Error('FontLoader indisponível');if(!font)font=await new THREE.FontLoader().loadAsync('https://cdn.jsdelivr.net/npm/three@0.128.0/examples/fonts/helvetiker_bold.typeface.json');const shapes=font.generateShapes(text,+$('textSize').value||28);shapes.forEach((s,i)=>addPart({name:`Texto ${i+1}`,shape:s,depth:+$('textDepth').value||8,color:$('textColor').value,finish:'gold'}));fit()}catch(e){fail('Erro ao criar texto 3D',e)}}
function removeSelected(){const p=selected();if(!p)return;root.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();parts=parts.filter(x=>x!==p);selectedId=null;if(transform)transform.detach();renderLayers();updateStats();status('Peça excluída')}
function duplicate(){const p=selected();if(!p)return;const q=addPart({name:p.name+' cópia',kind:p.kind,shape:p.shape,w:p.w,h:p.h,d:p.d,r:p.r,sides:p.sides,depth:p.depth,bevel:p.bevel,color:p.color,finish:p.finish});q.pos.copy(p.pos).add(new THREE.Vector3(8,-8,2));q.rot.copy(p.rot);q.scale.copy(p.scale);rebuild(q)}
function mirror(axis){const p=selected();if(!p)return;p.scale[axis]*=-1;p.mesh.scale.copy(p.scale);select(p.id)}
function centerSel(){const p=selected();if(!p)return;p.pos.x=0;p.pos.y=0;p.mesh.position.copy(p.pos);select(p.id)}
function ground(){const p=selected();if(!p)return;const b=new THREE.Box3().setFromObject(p.mesh);p.pos.z-=b.min.z;p.mesh.position.copy(p.pos);select(p.id)}
function relief(delta){const p=selected();if(!p||p.kind!=='extrude')return status('Relevo funciona em formas 2D/textos',true);p.depth=Math.max(.5,p.depth+delta);rebuild(p);select(p.id)}
function exportGLB(one=false){if(!THREE.GLTFExporter)return status('Exportador GLB indisponível',true);const obj=one?selected()?.mesh:root;if(!obj)return;new THREE.GLTFExporter().parse(obj,res=>{const blob=new Blob([res],{type:'model/gltf-binary'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(one?(selected()?.name||'peca'):'corel-3d')+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('GLB exportado')},{binary:true,onlyVisible:true})}
function saveProject(){const data=parts.map(p=>({name:p.name,kind:p.kind,w:p.w,h:p.h,d:p.d,r:p.r,sides:p.sides,depth:p.depth,bevel:p.bevel,color:p.color,finish:p.finish,pos:p.pos.toArray(),rot:[p.rot.x,p.rot.y,p.rot.z],scale:p.scale.toArray()}));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:'8.1',parts:data},null,2)],{type:'application/json'}));a.download='corel-3d-projeto.json';a.click()}
function snapshot(){renderer.render(scene,camera);const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='preview.png';a.click()}
$('addShape').onclick=addShape;$('addText').onclick=addText;$('delete').onclick=removeSelected;$('duplicate').onclick=duplicate;$('mx').onclick=()=>mirror('x');$('my').onclick=()=>mirror('y');$('mz').onclick=()=>mirror('z');$('center').onclick=centerSel;$('ground').onclick=ground;$('relief').onclick=()=>relief(2);$('basrelief').onclick=()=>relief(-2);$('exportAll').onclick=()=>exportGLB(false);$('exportOne').onclick=()=>exportGLB(true);$('saveProject').onclick=saveProject;$('snapshot').onclick=snapshot;
$('move').onclick=()=>transform&&transform.setMode('translate');$('rotate').onclick=()=>transform&&transform.setMode('rotate');$('scale').onclick=()=>transform&&transform.setMode('scale');
$('autorotate').onchange=e=>autorotate=e.target.checked;$('bg').onchange=e=>scene.background=new THREE.Color(e.target.value==='white'?0xffffff:e.target.value==='gray'?0x555b66:e.target.value==='blue'?0x0d2140:0x090d14);
$('name').onchange=e=>{const p=selected();if(!p)return;p.name=e.target.value||p.name;p.mesh.name=p.name;select(p.id)};$('depth').oninput=e=>{const p=selected();if(!p||p.kind!=='extrude')return;p.depth=+e.target.value;rebuild(p)};$('bevel').oninput=e=>{const p=selected();if(!p||p.kind!=='extrude')return;p.bevel=+e.target.value;rebuild(p)};$('color').oninput=e=>{const p=selected();if(!p)return;p.color=e.target.value;p.mesh.material.dispose();p.mesh.material=material(p);renderLayers()};$('finish').onchange=e=>{const p=selected();if(!p)return;p.finish=e.target.value;p.mesh.material.dispose();p.mesh.material=material(p)};
[['px','x'],['py','y'],['pz','z']].forEach(([i,a])=>$(i).onchange=e=>{const p=selected();if(!p)return;p.pos[a]=+e.target.value||0;p.mesh.position.copy(p.pos)});[['rx','x'],['ry','y'],['rz','z']].forEach(([i,a])=>$(i).onchange=e=>{const p=selected();if(!p)return;p.rot[a]=THREE.MathUtils.degToRad(+e.target.value||0);p.mesh.rotation.copy(p.rot)});[['sx','x'],['sy','y'],['sz','z']].forEach(([i,a])=>$(i).onchange=e=>{const p=selected();if(!p)return;p.scale[a]=+e.target.value||1;p.mesh.scale.copy(p.scale)});
renderer.domElement.addEventListener('pointerdown',e=>{if(!parts.length)return;const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(parts.map(p=>p.mesh),false)[0];if(hit)select(hit.object.userData.partId)});
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{$('fileName').textContent=f.name;if(f.type.startsWith('image/')){status('Importação de imagem será reativada na próxima correção estável.');return}if(f.name.toLowerCase().endsWith('.svg')){if(!THREE.SVGLoader)throw new Error('SVGLoader indisponível');const data=new THREE.SVGLoader().parse(await f.text());data.paths.forEach((path,pi)=>THREE.SVGLoader.createShapes(path).forEach((s,si)=>addPart({name:`SVG ${pi+1}.${si+1}`,shape:s,depth:8,color:'#'+path.color.getHexString()})));fit();status('SVG importado')}else status('Use SVG por enquanto; outros formatos serão reativados depois.',true)}catch(err){fail('Erro ao importar arquivo',err)}};
const eng=$('engine');eng.textContent='MOTOR 3D ATIVO ✓';eng.style.background='#103322';eng.style.color='#72e7a9';status('Motor 3D carregado. Teste: Adicionar forma.');
}catch(e){fail('Falha ao inicializar o motor 3D',e)}
})();